name: External Trigger

on:
  repository_dispatch:
    types:
      - deploy-request

jobs:
  external-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Show environment
        run: |
          echo "External deployment request received."
          echo "Environment: ${{ github.event.client_payload.environment }}"

      - name: Deploy
        run: |
          echo "Starting deployment..."
          echo "Deployment environment:"
          echo "${{ github.event.client_payload.environment }}"
