#Workflow
name: Hello

#on tells when the workflow should run
on:
  workflow_dispatch: 

#job tells what the workflow should do there can be one or more than one jobs hence we write jobs 
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"
      
  
