name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is set
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: Try printing secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "Secret value: $MY_SECRET"
